import React from "react";

export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCHED_ERROR: "PROFILE_DATA_FETCHED_ERROR",
    USER_DATA_UPDATED: "PROFILE_DATA_UPDATED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
  },
};
